
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
branches:
  except:
    - master
  services:
    - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org=3.2.14
